[package]
name = "test_vessel"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
vessels = { path = "../../" }
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
serde = { version = "1.0.101", features = ["derive"] }
