[package]
name = "native_core_test"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
vessels = { path = "../../", features = ["core"] }
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
