name: Build 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcairo2-dev libpango1.0-dev libpangocairo-1.0-0 libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev
        rustup default stable
        rustup target add wasm32-unknown-unknown
        cargo install cargo-web
    - name: Build for native
      run: cargo build --verbose
    - name: Build for web
      run: cargo web build --verbose
    - name: Build documentation
      run: |
        cargo rustdoc
        mv target/doc/vessels target/doc/docs
        echo "<!DOCTYPE html><html><head><script>window.location.replace(\"/vessels/docs\");</script></head></html>" > target/doc/index.html
    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: target/doc
